import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const packageJson = require('../../package.json') as { version: string };

export const PACKAGE_VERSION: string = packageJson.version;

/**
 * Distribution mode for the CLI.
 * - PROD_DISTRO: Public npm registry (npmjs.org)
 * - PRIVATE_DEV_DISTRO: GitHub Package Registry (private/scoped)
 */
export type DistroMode = 'PROD_DISTRO' | 'PRIVATE_DEV_DISTRO';

export const DISTRO_MODE: DistroMode = 'PROD_DISTRO';

/**
 * Configuration for each distribution mode.
 */
export const DISTRO_CONFIG = {
  PROD_DISTRO: {
    packageName: '@aws/agentcore',
    registryUrl: 'https://registry.npmjs.org',
    installCommand: 'npm install -g @aws/agentcore@latest',
  },
  PRIVATE_DEV_DISTRO: {
    packageName: '@aws/agentcore',
    registryUrl: 'https://npm.pkg.github.com',
    installCommand: 'npm install -g @aws/agentcore@latest --registry=https://npm.pkg.github.com',
  },
} as const;

export function getNpmDistTag(): string {
  return PACKAGE_VERSION.includes('-') ? 'preview' : 'latest';
}

/**
 * Get the current distribution configuration.
 */
export function getDistroConfig() {
  const base = DISTRO_CONFIG[DISTRO_MODE];
  const distTag = getNpmDistTag();
  return {
    ...base,
    distTag,
    installCommand: base.installCommand.replace('@latest', `@${distTag}`),
  };
}

/**
 * Directory name where the CDK project is generated by `agentcore create`.
 * This is relative to CONFIG_DIR (agentcore/cdk/).
 */
export const CDK_PROJECT_DIR = 'cdk';

/**
 * CDK app entry point relative to the CDK project directory.
 * Points to the compiled JS in the dist directory.
 */
export const CDK_APP_ENTRY = 'dist/bin/cdk.js';

/**
 * Current schema version for AgentCore configuration files.
 */
export const SCHEMA_VERSION = 1;

/**
 * Default runtime endpoint name used in log group paths and console URLs.
 */
export const DEFAULT_ENDPOINT_NAME = 'DEFAULT';

export const TELEMETRY_ENDPOINT = 'https://telemetry.agentcore.aws.dev';

/**
 * Color gating: emit ANSI codes only when both streams are attached to a terminal.
 * Uses AND so that redirecting either stream (e.g. `2> log.txt`) disables colors,
 * preventing escape codes from leaking into files.
 * - FORCE_COLOR: override to enable colors regardless of TTY (e.g. in CI/tests).
 * - NO_COLOR: standard (no-color.org) override to strip all color output.
 */
const stylingEnabled =
  !!process.env.FORCE_COLOR || (!process.env.NO_COLOR && !!process.stdout.isTTY && !!process.stderr.isTTY);
const style = (code: string) => (stylingEnabled ? code : '');

/** ANSI escape codes for console output. Auto-disabled when piped or NO_COLOR is set. */
export const ANSI = {
  red: style('\x1b[31m'),
  green: style('\x1b[32m'),
  yellow: style('\x1b[33m'),
  cyan: style('\x1b[36m'),
  dim: style('\x1b[2m'),
  reset: style('\x1b[0m'),
  // Terminal control sequences (always active — only used when TTY is confirmed)
  clearLine: '\x1b[K',
  enterAltScreen: '\x1b[?1049h\x1b[H',
  exitAltScreen: '\x1b[?1049l',
  showCursor: '\x1b[?25h',
  // TUI gradient colors
  brightYellow: style('\x1b[38;2;255;255;0m'),
  mutedYellow: style('\x1b[38;2;255;255;85m'),
  darkYellow: style('\x1b[38;2;218;218;0m'),
} as const;
